/**
 * Cloudflare Function - user API
 * Wraps the Vercel handler for Cloudflare compatibility
 * Auto-generated by scripts/generate-cloudflare-functions.js
 */

import { createCloudflareHandler } from "../../api/_lib/adapter.js";
import vercelHandler from "../../api/user.js";

export const onRequest = createCloudflareHandler(vercelHandler);
